version: "3.7"

services:
  google-address-api:
    container_name: google-address-api
    build: .
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/google-address-api
    ports:
    - 8080:8080
    depends_on:
      - mongodb
    networks:
      - google-address-net

  mongodb:
    image: mongo
    container_name: google-address-mongodb
    ports:
    - 27017:27017
    networks:
      - google-address-net

networks:
  google-address-net:
    driver: bridge